### PR TITLE
Package Hypnos for DFU (draft)

### PR DESCRIPTION
**Pull request by endian-albin**
This should prepare Hypnos for both being packaged as a DFU image and confirming the new image after boot. Additional commits will be necessary.

### CODE REVIEW

**Comment by endian-albin** [comment]
In order for Hypnos to be bootable from the next factory image we need to patch the binary (see https://github.com/endian-albin/pinetime-hypnos/issues/36#issuecomment-678996986). If/when patching is no longer needed, we'll make changes as needed. I'll add patching and packaging instructions to this branch based on lupyuen's work. I see no point in merging this before FOTA is implemented in the application though, so that should be the next step.

**Comment by sdorre** [comment]
Just my grain of salt:
Have you seen the configuration option in Zephyr ?

```
config BOOTLOADER_MCUBOOT
	bool "MCUboot bootloader support"
	select USE_DT_CODE_PARTITION
	help
	  This option signifies that the target uses MCUboot as a bootloader,
	  or in other words that the image is to be chain-loaded by MCUboot.
	  This sets several required build system and Device Tree options in
	  order for the image generated to be bootable using the MCUboot open
	  source bootloader. Currently this includes:

	    * Setting TEXT_SECTION_OFFSET to a default value that allows space
	      for the MCUboot image header
	    * Activating SW_VECTOR_RELAY on Cortex-M0 (or Armv8-M baseline)
	      targets with no built-in vector relocation mechanisms
```

```
config SW_VECTOR_RELAY
	bool "Enable Software Vector Relay"
	default y if BOOTLOADER_MCUBOOT
	depends on ARMV6_M_ARMV8_M_BASELINE && !(CPU_CORTEX_M0_HAS_VECTOR_TABLE_REMAP || CPU_CORTEX_M_HAS_VTOR)
	help
	  Add Vector Table relay handler and relay vector table, to
	  relay interrupts based on a vector table pointer. This is only
	  required for Cortex-M0 (or an Armv8-M baseline core) with no hardware
	  vector table relocation mechanisms or for Cortex-M0+
	  (or an Armv8-M baseline core) with no VTOR and no other hardware
	  relocation table mechanisms.
```

```
config TEXT_SECTION_OFFSET
	hex
	prompt "TEXT section offset" if !BOOTLOADER_MCUBOOT
	default 0x200 if BOOTLOADER_MCUBOOT
	default 0
	help
	  If the application is built for chain-loading by a bootloader this
	  variable is required to be set to value that leaves sufficient
	  space between the beginning of the image and the start of the .text
	  section to store an image header or any other metadata.
	  In the particular case of the MCUboot bootloader this reserves enough
	  space to store the image header, which should also meet vector table
	  alignment requirements on most ARM targets, although some targets
	  may require smaller or larger values.
```

I guess that is what we need isn't it ?

**Comment by endian-albin** [comment]
@sdorre: that's an interesting finding. I just tried to set `CONFIG_TEXT_SECTION_OFFSET` to zero but build system reset it to `0x200`, apparently because I also have `CONFIG_BOOTLOADER_MCUBOOT=y`.

**Comment by sdorre** [comment]
> @sdorre: that's an interesting finding. I just tried to set `CONFIG_TEXT_SECTION_OFFSET` to zero but build system reset it to `0x200`, apparently because I also have `CONFIG_BOOTLOADER_MCUBOOT=y`.

Yeah it's because of the default value. 
If we want to change it, it should be defined before the main Kconfig.
You can change the file `Kconfig.pinetime`, to be like:

```
menu "Pinetime"

config TEXT_SECTION_OFFSET
	hex
	prompt "TEXT section offset" if !BOOTLOADER_MCUBOOT
	default 0x20 if BOOTLOADER_MCUBOOT
	default 0
	help
	  If the application is built for chain-loading by a bootloader this
	  variable is required to be set to value that leaves sufficient
	  space between the beginning of the image and the start of the .text
	  section to store an image header or any other metadata.
	  In the particular case of the MCUboot bootloader this reserves enough
	  space to store the image header, which should also meet vector table
	  alignment requirements on most ARM targets, although some targets
	  may require smaller or larger values.

rsource "drivers/sensor/Kconfig"
rsource "subsys/Kconfig"

endmenu
```

and that should do the job. But If the alignment is made with a default of `0x200` there should be a good reason for that. (At least for the VTOR alignment)
So I would try to keep it that way even if that means changing the bootloader. Or we set it to `0x20` for now and will change it later on to the default value `0x200` ?

**Comment by endian-albin** [comment]
I'm closing this PR in favour of #68.

**Pull request closed without merging**
