### PR TITLE
Upgrade to zephyr v2.4.0

### PR DESCRIPTION
**Pull request by endian-albin**
This upgrades Zephyr to the current master until the final version of zephyr v2.4.0 is released. I've made a lot of compatibility changes all over the place, including fixing the touch sensor driver. We also move from LVGL version 6 to 7 and so I had to make various changes to the graphics code. I couldn't make the background anything but white so I added a background image instead. Image management appear to work now.

### CODE REVIEW

**Comment by endian-albin** [comment]
@sdorre, I'm sorry to ask you for reviewing such a massive PR, but I've tried to split the changes into multiple relevant commits at least.

**Comment by sdorre** [comment]
There is an example in `lv_theme_mono.c` To set Background color and how to init a style.
Something like:
```
static void basic_init(void)
{
    style_init_reset(&styles->scr);
    lv_style_set_bg_opa(&styles->scr, LV_STATE_DEFAULT, LV_OPA_COVER);
    lv_style_set_bg_color(&styles->scr, LV_STATE_DEFAULT, BG_COLOR);
    lv_style_set_text_color(&styles->scr, LV_STATE_DEFAULT, FG_COLOR);
    lv_style_set_value_color(&styles->scr, LV_STATE_DEFAULT, FG_COLOR);

    style_init_reset(&styles->bg);
```

**Comment by endian-albin** [comment]
> There is an example in `lv_theme_mono.c` To set Background color and how to init a style.
> 
> Something like:
> 
> ```
> 
> static void basic_init(void)
> 
> {
> 
>     style_init_reset(&styles->scr);
> 
>     lv_style_set_bg_opa(&styles->scr, LV_STATE_DEFAULT, LV_OPA_COVER);
> 
>     lv_style_set_bg_color(&styles->scr, LV_STATE_DEFAULT, BG_COLOR);
> 
>     lv_style_set_text_color(&styles->scr, LV_STATE_DEFAULT, FG_COLOR);
> 
>     lv_style_set_value_color(&styles->scr, LV_STATE_DEFAULT, FG_COLOR);
> 
> 
> 
>     style_init_reset(&styles->bg);
> 
> ```

Yes, I think we also need to enable a theme in prj.conf. I'll give it a try.

**Comment by endian-albin** [comment]
I've restored the font size and the simple black background. For the latter I only needed to add `CONFIG_LVGL_USE_THEME_MONO=y`

**Review by sdorre — APPROVED** [review]
It looks good so far

**Comment by endian-albin** [comment]
> It looks good so far

Thanks! I'll just wait for the final v2.4.0 release (which should come very soon) and update west.yml before merging.

**Pull request merged**
