### PR TITLE
Github CI: build and upload p8 after pinetime

### LINKED ISSUE #61: Github CI: avoid duplication of work
It's wasteful to duplicate all the steps for building pinetime and p8 when only the board is different. Try to build one after the other.

### PR DESCRIPTION
**Pull request by endian-albin**
Fixes #61.

@sdorre, @MirkoCovizzi, what do you think?

### CODE REVIEW

**Comment by endian-albin** [comment]
I've tested installing both hex files can can run the firmwares. With the pinetime version the button works but not on the p8 build, as expected.

**Comment by MirkoCovizzi** [comment]
@endian-albin Sorry, what was the issue here exactly?

**Comment by endian-albin** [comment]
I've tested installing both hex files can can run the firmwares. With the pinetime version the button works but not on the p8 build, as expected.

> @endian-albin Sorry, what was the issue here exactly?

The workflow version using "matrix" to build both boards duplicated many west commands which wasn't necessary. This restores how it was previously but simply build and uploads each of the boards one after the other.

**Comment by MirkoCovizzi** [comment]
@endian-albin If you take a look at the past GitHub Action executions, you can see that it takes pretty much the same time to complete the tasks when done in parallel compared to compiling sequentially as this workflow shows. The advantage of using a matrix is that the workflow markup is easier to understand and manage and, as I wrote earlier, it has parallelized execution. If in the near future someone else comes and proposes to add another device similar to the PineTime and the P8, it will be much easier to integrate in the workflow. Using combination matrixes in GitHub workflows is a very common and very flexible pattern.

**Comment by endian-albin** [comment]
> @endian-albin If you take a look at the past GitHub Action executions, you can see that it takes pretty much the same time to complete the tasks when done in parallel (with the matrix) compared to compiling sequentially as this workflow proposes.

That's true when you just count the time of the entire build (ca 2 minutes), but if you sum the two parallel build times, then you land at about 3 minutes in total execution time. I'm the kind of person who makes sure to turn off the lights when leaving a room :)

>The advantage of using a matrix is that the workflow markup is easier to understand, manage and, as I wrote earlier, it has parallelized execution.

Yes, I'm sure it has some uses, especially when calculating/building something very different, such as a companion app.

>If in the near future someone else comes and proposes to add another device similar to the PineTime and the P8, it will be much easier to integrate it in the workflow. Using combination matrixes in GitHub workflows is a very common and very flexible pattern.

I'm not against its use in general; I just feel that it's not warranted when such a big part of the job is duplicated.

**Comment by endian-albin** [comment]
I no longer feel this is justified. There are other pressing issues...

**Pull request closed without merging**
